INSERT INTO trad (key, lang, translation) VALUES ('title_about', 'fr', 'À propos - Fontainebleau') ON CONFLICT (key, lang) DO NOTHING;
INSERT INTO trad (key, lang, translation) VALUES ('mentions_title', 'fr', 'Mentions légales') ON CONFLICT (key, lang) DO NOTHING;
INSERT INTO trad (key, lang, translation) VALUES ('mentions_paragraph1', 'fr', 'Ce site et son contenu sont la propriété intellectuelle de L''Université Gustave Eiffel et de l''UNESCO. Toute reproduction ou représentation totale ou partielle de ce site ou de son contenu est interdite sans autorisation préalable.') ON CONFLICT (key, lang) DO NOTHING;
INSERT INTO trad (key, lang, translation) VALUES ('contact_title', 'fr', 'Nous contacter') ON CONFLICT (key, lang) DO NOTHING;
INSERT INTO trad (key, lang, translation) VALUES ('name_label', 'fr', 'Votre nom') ON CONFLICT (key, lang) DO NOTHING;
INSERT INTO trad (key, lang, translation) VALUES ('email_label', 'fr', 'Email') ON CONFLICT (key, lang) DO NOTHING;
INSERT INTO trad (key, lang, translation) VALUES ('message_label', 'fr', 'Votre message') ON CONFLICT (key, lang) DO NOTHING;
INSERT INTO trad (key, lang, translation) VALUES ('submit_button', 'fr', 'Envoyer') ON CONFLICT (key, lang) DO NOTHING;
INSERT INTO trad (key, lang, translation) VALUES ('fin_section', 'fr', 'Nous remercions toute l''équipe pédagogique de l''université Gustave Eiffel et en particulier nos professeurs : Monsieur Ettayeb ainsi que Monsieur Cessy de nous avoir accompagné dans ce projet.') ON CONFLICT (key, lang) DO NOTHING;
INSERT INTO trad (key, lang, translation) VALUES ('team_jawed', 'fr', 'Chef d''équipe / Organisateur') ON CONFLICT (key, lang) DO NOTHING;
INSERT INTO trad (key, lang, translation) VALUES ('team_kirushikesan', 'fr', 'Concepteur / Perfectionniste') ON CONFLICT (key, lang) DO NOTHING;
INSERT INTO trad (key, lang, translation) VALUES ('team_victor', 'fr', 'Expert / Coordinateur') ON CONFLICT (key, lang) DO NOTHING;
INSERT INTO trad (key, lang, translation) VALUES ('title_about', 'en', 'About - Fontainebleau') ON CONFLICT (key, lang) DO NOTHING;
INSERT INTO trad (key, lang, translation) VALUES ('header_title', 'en', 'Fontainebleau - UNESCO') ON CONFLICT (key, lang) DO NOTHING;
INSERT INTO trad (key, lang, translation) VALUES ('mentions_title', 'en', 'Legal Mentions') ON CONFLICT (key, lang) DO NOTHING;
INSERT INTO trad (key, lang, translation) VALUES ('mentions_paragraph1', 'en', 'This site and its content are the intellectual property of Gustave Eiffel University and UNESCO. Any total or partial reproduction or representation of this site or its content is prohibited without prior authorization.') ON CONFLICT (key, lang) DO NOTHING;
INSERT INTO trad (key, lang, translation) VALUES ('contact_title', 'en', 'Contact Us') ON CONFLICT (key, lang) DO NOTHING;
INSERT INTO trad (key, lang, translation) VALUES ('name_label', 'en', 'Your Name') ON CONFLICT (key, lang) DO NOTHING;
INSERT INTO trad (key, lang, translation) VALUES ('email_label', 'en', 'Email') ON CONFLICT (key, lang) DO NOTHING;
INSERT INTO trad (key, lang, translation) VALUES ('message_label', 'en', 'Your Message') ON CONFLICT (key, lang) DO NOTHING;
INSERT INTO trad (key, lang, translation) VALUES ('submit_button', 'en', 'Send') ON CONFLICT (key, lang) DO NOTHING;
INSERT INTO trad (key, lang, translation) VALUES ('fin_section', 'en', 'We thank the entire teaching team of Gustave Eiffel University and in particular our professors: Mr. Ettayeb and Mr. Cessy for accompanying us in this project.') ON CONFLICT (key, lang) DO NOTHING;
INSERT INTO trad (key, lang, translation) VALUES ('team_jawed', 'en', 'Team Leader / Organizer') ON CONFLICT (key, lang) DO NOTHING;
INSERT INTO trad (key, lang, translation) VALUES ('team_kirushikesan', 'en', 'Designer / Perfectionist') ON CONFLICT (key, lang) DO NOTHING;
INSERT INTO trad (key, lang, translation) VALUES ('team_victor', 'en', 'Expert / Coordinator') ON CONFLICT (key, lang) DO NOTHING;
INSERT INTO trad (key, lang, translation) VALUES ('title_about', 'es', 'Acerca de - Fontainebleau') ON CONFLICT (key, lang) DO NOTHING;
INSERT INTO trad (key, lang, translation) VALUES ('header_title', 'es', 'Fontainebleau - UNESCO') ON CONFLICT (key, lang) DO NOTHING;
INSERT INTO trad (key, lang, translation) VALUES ('mentions_title', 'es', 'Aviso Legal') ON CONFLICT (key, lang) DO NOTHING;
INSERT INTO trad (key, lang, translation) VALUES ('mentions_paragraph1', 'es', 'Este sitio y su contenido son propiedad intelectual de la Universidad Gustave Eiffel y de la UNESCO. Cualquier reproducción total o parcial o representación de este sitio o su contenido está prohibida sin autorización previa.') ON CONFLICT (key, lang) DO NOTHING;
INSERT INTO trad (key, lang, translation) VALUES ('contact_title', 'es', 'Contáctenos') ON CONFLICT (key, lang) DO NOTHING;
INSERT INTO trad (key, lang, translation) VALUES ('name_label', 'es', 'Su nombre') ON CONFLICT (key, lang) DO NOTHING;
INSERT INTO trad (key, lang, translation) VALUES ('email_label', 'es', 'Correo electrónico') ON CONFLICT (key, lang) DO NOTHING;
INSERT INTO trad (key, lang, translation) VALUES ('message_label', 'es', 'Su mensaje') ON CONFLICT (key, lang) DO NOTHING;
INSERT INTO trad (key, lang, translation) VALUES ('submit_button', 'es', 'Enviar') ON CONFLICT (key, lang) DO NOTHING;
INSERT INTO trad (key, lang, translation) VALUES ('fin_section', 'es', 'Agradecemos a todo el equipo docente de la Universidad Gustave Eiffel y en particular a nuestros profesores: el Sr. Ettayeb y el Sr. Cessy por acompañarnos en este proyecto.') ON CONFLICT (key, lang) DO NOTHING;
INSERT INTO trad (key, lang, translation) VALUES ('team_jawed', 'es', 'Líder del equipo / Organizador') ON CONFLICT (key, lang) DO NOTHING;
INSERT INTO trad (key, lang, translation) VALUES ('team_kirushikesan', 'es', 'Diseñador / Perfeccionista') ON CONFLICT (key, lang) DO NOTHING;
INSERT INTO trad (key, lang, translation) VALUES ('team_victor', 'es', 'Experto / Coordinador') ON CONFLICT (key, lang) DO NOTHING;