
-- Insertion des données
INSERT INTO images (titre, path) VALUES
('jawed_about', 'https://i.ibb.co/NVJc781/jawed.jpg'),
('kirushi_about', 'https://i.ibb.co/Mps0K4J/kirushikesan.png'),
('victor_about', 'https://i.ibb.co/xYyv9bD/victor.png'),
('escalier_architecture', 'https://i.ibb.co/WnmxpwC/escalier-fer-a-cheval.jpg'),
('galerie_des_cerfs_architecture', 'https://i.ibb.co/RpTPcqD/galerie-des-cerfs.jpg'),
('galerie_francois_architecture', 'https://i.ibb.co/K7fY6q5/galerie-francois-1er.jpg'),
('cheminee_architecture', 'https://i.ibb.co/zrcmsGH/salle-cheminee.png'),
('bg_architecture_architecture', 'https://i.ibb.co/1GWzMhf/bg.png'),
('salle_trone_architecture', 'https://i.ibb.co/NWBxLW5/chambre-royale.png'),
('cour_architecture', 'https://i.ibb.co/BNML0Mh/cour.png'),
('francois_histoire', 'https://i.ibb.co/5WKznQH/francois.png'),
('cour_adieu_histoire', 'https://i.ibb.co/Qms7M5n/henri.png'),
('abdication_histoire', 'https://i.ibb.co/cDzJDq9/napoleon.png'),
('nos_jours_histoire', 'https://i.ibb.co/HTztF93/nos-jours.png'),
('allemagne_histoire', 'https://i.ibb.co/vZTw9PP/occupation-allemende.png'),
('bg_histoire', 'https://i.ibb.co/8mYt6jP/bg-histoire.png'),
('charle_histoire', 'https://i.ibb.co/Gthb3Jz/charles.png'),
('creation_histoire', 'https://i.ibb.co/jRWjJGX/creation.png'),
('grotte_pin_jardin', 'https://i.ibb.co/xSbq93C/grotte-pins.png'),
('parc_jardin', 'https://i.ibb.co/zHt1qCs/parc.png'),
('porte_baptistere_jardin', 'https://i.ibb.co/WsSSqdM/porte-baptistere.png'),
('cour_offices_jardin', 'https://i.ibb.co/VtbHQHw/cour-offices.png'),
('etang_carpes_jardin', 'https://i.ibb.co/rtFPyTQ/etang-carpes.png'),
('grand_parterre_jardin', 'https://i.ibb.co/zR15XVm/grand-parterre.png'),
('train_plan', 'https://i.ibb.co/09gLsHV/background.jpg'),
('unesco_footer', 'https://i.ibb.co/2ksmdbf/unesco.png'),
('foret_accueil', 'https://i.ibb.co/Ny8qHVK/foret.png'),
('francois_premier_accueil', 'https://i.ibb.co/H4ct28N/francois.jpg'),
('logo_gustave_iut_footer', 'https://i.ibb.co/1msFMd8/iut-logo.png'),
('logo_iut_footer', 'https://i.ibb.co/m9wgmxw/logo.png'),
('logo_mcn_footer', 'https://i.ibb.co/f41dVsm/mcn.png'),
('residence_royale_architecture', 'https://i.ibb.co/LCQzkSh/residence-royale.png'),
('drapeau_royaume_uni_header', 'https://i.ibb.co/XjycGc4/royaume-uni.png'),
('drapeau_france_header', 'https://i.postimg.cc/4Kh08sBZ/fr.png'),
('drapeau_espagne_header', 'https://i.postimg.cc/KzwStsJx/es.png');